version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
      day: friday
